- name: Install OpenVPN
  package:
   name: "{{ item }}"
   state: present
  with_items:
    - openvpn
    - openssl
    - iptables
    - bridge-utils

- name: Create drop-in directory
  file:
    path: /etc/systemd/system/openvpn@.service.d/
    state: directory

- name: Install drop-in unit
  template:
    src: restart.conf.j2
    dest: /etc/systemd/system/openvpn@.service.d/restart.conf
  notify: Reload systemd

- name: Install LDAP plugin
  package:
   name: openvpn-auth-ldap
   state: present
  when: openvpn_ldap is defined

- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: yes
